name = "redon_tech/emergency_vehicle_creator"
version = "0.1.0"
authors = ["parker02311"]
license = "MIT"

[target]
environment = "roblox"

[indices]
default = "https://github.com/pesde-pkg/index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.1.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.4.4", target = "lune" }

[dependencies]
redon-ui = { wally = "wally#redon-tech/redon-ui", version = "^0.1.0-alpha.7" }
fusion = { wally = "wally#elttob/fusion", version = "^0.3.0" }
